export const GET_CLASSROOMLIST_REQUEST_SCHOOL =
  "GET_CLASSROOMLIST_REQUEST_SCHOOL";
export const GET_CLASSROOMLIST_SUCCESS_SCHOOL =
  "GET_CLASSROOMLIST_SUCCESS_SCHOOL";
export const GET_CLASSROOMLIST_FAIL_SCHOOL = "GET_CLASSROOMLIST_FAIL_SCHOOL";

export const GET_CLASSROOMS_REQUEST_SCHOOL = "GET_CLASSROOMS_REQUEST_SCHOOL";
export const GET_CLASSROOMS_SUCCESS_SCHOOL = "GET_CLASSROOMS_SUCCESS_SCHOOL";
export const GET_CLASSROOMS_FAIL_SCHOOL = "GET_CLASSROOMS_FAIL_SCHOOL";

export const POST_CLASSROOMS_REQUEST_SCHOOL = "POST_CLASSROOMS_REQUEST_SCHOOL";
export const POST_CLASSROOMS_SUCCESS_SCHOOL = "POST_CLASSROOMS_SUCCESS_SCHOOL";
export const POST_CLASSROOMS_FAIL_SCHOOL = "POST_CLASSROOMS_FAIL_SCHOOL";

export const DELETE_CLASSROOMS_REQUEST_SCHOOL =
  "DELETE_CLASSROOMS_REQUEST_SCHOOL";
export const DELETE_CLASSROOMS_SUCCESS_SCHOOL =
  "DELETE_CLASSROOMS_SUCCESS_SCHOOL";
export const DELETE_CLASSROOMS_FAIL_SCHOOL = "DELETE_CLASSROOMS_FAIL_SCHOOL";

export const PUT_CLASSROOMS_REQUEST_SCHOOL = "PUT_CLASSROOMS_REQUEST_SCHOOL";
export const PUT_CLASSROOMS_SUCCESS_SCHOOL = "PUT_CLASSROOMS_SUCCESS_SCHOOL";
export const PUT_CLASSROOMS_FAIL_SCHOOL = "PUT_CLASSROOMS_FAIL_SCHOOL";

export const CLEAN_CLASSROOMS_SCHOOL = "CLEAN_CLASSROOMS_SCHOOL";
