export const GET_DASHBOARDSTATS_REQUEST_SCHOOL =
  "GET_DASHBOARDSTATS_REQUEST_SCHOOL";
export const GET_DASHBOARDSTATS_SUCCESS_SCHOOL =
  "GET_DASHBOARDSTATS_SUCCESS_SCHOOL";
export const GET_DASHBOARDSTATS_FAIL_SCHOOL = "GET_DASHBOARDSTATS_FAIL_SCHOOL";
