export const GET_LESSONS_REQUEST_SCHOOL = "GET_LESSONS_REQUEST_SCHOOL";
export const GET_LESSONS_SUCCESS_SCHOOL = "GET_LESSONS_SUCCESS_SCHOOL";
export const GET_LESSONS_FAIL_SCHOOL = "GET_LESSONS_FAIL_SCHOOL";

export const POST_LESSONS_REQUEST_SCHOOL = "POST_LESSONS_REQUEST_SCHOOL";
export const POST_LESSONS_SUCCESS_SCHOOL = "POST_LESSONS_SUCCESS_SCHOOL";
export const POST_LESSONS_FAIL_SCHOOL = "POST_LESSONS_FAIL_SCHOOL";

export const DELETE_LESSONS_REQUEST_SCHOOL = "DELETE_LESSONS_REQUEST_SCHOOL";
export const DELETE_LESSONS_SUCCESS_SCHOOL = "DELETE_LESSONS_SUCCESS_SCHOOL";
export const DELETE_LESSONS_FAIL_SCHOOL = "DELETE_LESSONS_FAIL_SCHOOL";

export const PUT_LESSONS_REQUEST_SCHOOL = "PUT_LESSONS_REQUEST_SCHOOL";
export const PUT_LESSONS_SUCCESS_SCHOOL = "PUT_LESSONS_SUCCESS_SCHOOL";
export const PUT_LESSONS_FAIL_SCHOOL = "PUT_LESSONS_FAIL_SCHOOL";

export const CLEAN_LESSONS_SCHOOL = "CLEAN_LESSONS_SCHOOL";
