export const GET_STUDENTS_REQUEST_SCHOOL = "GET_STUDENTS_REQUEST_SCHOOL";
export const GET_STUDENTS_SUCCESS_SCHOOL = "GET_STUDENTS_SUCCESS_SCHOOL";
export const GET_STUDENTS_FAIL_SCHOOL = "GET_STUDENTS_FAIL_SCHOOL";

export const POST_STUDENTS_REQUEST_SCHOOL = "POST_STUDENTS_REQUEST_SCHOOL";
export const POST_STUDENTS_SUCCESS_SCHOOL = "POST_STUDENTS_SUCCESS_SCHOOL";
export const POST_STUDENTS_FAIL_SCHOOL = "POST_STUDENTS_FAIL_SCHOOL";

export const PUT_STUDENTS_REQUEST_SCHOOL = "PUT_STUDENTS_REQUEST_SCHOOL";
export const PUT_STUDENTS_SUCCESS_SCHOOL = "PUT_STUDENTS_SUCCESS_SCHOOL";
export const PUT_STUDENTS_FAIL_SCHOOL = "PUT_STUDENTS_FAIL_SCHOOL";

export const DELETE_STUDENTS_REQUEST_SCHOOL = "DELETE_STUDENTS_REQUEST_SCHOOL";
export const DELETE_STUDENTS_SUCCESS_SCHOOL = "DELETE_STUDENTS_SUCCESS_SCHOOL";
export const DELETE_STUDENTS_FAIL_SCHOOL = "DELETE_STUDENTS_FAIL_SCHOOL";

export const CLEAN_STUDENTS_SCHOOL = "CLEAN_STUDENTS_SCHOOL";
