export const GET_TEACHERLIST_REQUEST_SCHOOL = "GET_TEACHERLIST_REQUEST_SCHOOL";
export const GET_TEACHERLIST_SUCCESS_SCHOOL = "GET_TEACHERLIST_SUCCESS_SCHOOL";
export const GET_TEACHERLIST_FAIL_SCHOOL = "GET_TEACHERLIST_FAIL_SCHOOL";

export const GET_TEACHERS_REQUEST_SCHOOL = "GET_TEACHERS_REQUEST_SCHOOL";
export const GET_TEACHERS_SUCCESS_SCHOOL = "GET_TEACHERS_SUCCESS_SCHOOL";
export const GET_TEACHERS_FAIL_SCHOOL = "GET_TEACHERS_FAIL_SCHOOL";

export const POST_TEACHERS_REQUEST_SCHOOL = "POST_TEACHERS_REQUEST_SCHOOL";
export const POST_TEACHERS_SUCCESS_SCHOOL = "POST_TEACHERS_SUCCESS_SCHOOL";
export const POST_TEACHERS_FAIL_SCHOOL = "POST_TEACHERS_FAIL_SCHOOL";

export const DELETE_TEACHERS_REQUEST_SCHOOL = "DELETE_TEACHERS_REQUEST_SCHOOL";
export const DELETE_TEACHERS_SUCCESS_SCHOOL = "DELETE_TEACHERS_SUCCESS_SCHOOL";
export const DELETE_TEACHERS_FAIL_SCHOOL = "DELETE_TEACHERS_FAIL_SCHOOL";

export const PUT_TEACHERS_REQUEST_SCHOOL = "PUT_TEACHERS_REQUEST_SCHOOL";
export const PUT_TEACHERS_SUCCESS_SCHOOL = "PUT_TEACHERS_SUCCESS_SCHOOL";
export const PUT_TEACHERS_FAIL_SCHOOL = "PUT_TEACHERS_FAIL_SCHOOL";

export const CLEAN_TEACHERS_SCHOOL = "CLEAN_TEACHERS_SCHOOL";
