export const GET_EXAMS_REQUEST_TEACHER = "GET_EXAMS_REQUEST_TEACHER";
export const GET_EXAMS_SUCCESS_TEACHER = "GET_EXAMS_SUCCESS_TEACHER";
export const GET_EXAMS_FAIL_TEACHER = "GET_EXAMS_FAIL_TEACHER";

export const POST_EXAMS_REQUEST_TEACHER = "POST_EXAMS_REQUEST_TEACHER";
export const POST_EXAMS_SUCCESS_TEACHER = "POST_EXAMS_SUCCESS_TEACHER";
export const POST_EXAMS_FAIL_TEACHER = "POST_EXAMS_FAIL_TEACHER";

export const DELETE_EXAMS_REQUEST_TEACHER = "DELETE_EXAMS_REQUEST_TEACHER";
export const DELETE_EXAMS_SUCCESS_TEACHER = "DELETE_EXAMS_SUCCESS_TEACHER";
export const DELETE_EXAMS_FAIL_TEACHER = "DELETE_EXAMS_FAIL_TEACHER";

export const PUT_EXAMS_REQUEST_TEACHER = "PUT_EXAMS_REQUEST_TEACHER";
export const PUT_EXAMS_SUCCESS_TEACHER = "PUT_EXAMS_SUCCESS_TEACHER";
export const PUT_EXAMS_FAIL_TEACHER = "PUT_EXAMS_FAIL_TEACHER";

export const CLEAN_EXAMS_TEACHER = "CLEAN_EXAMS_TEACHER";
