export const GET_HOMEWORKS_REQUEST_TEACHER = "GET_HOMEWORKS_REQUEST_TEACHER";
export const GET_HOMEWORKS_SUCCESS_TEACHER = "GET_HOMEWORKS_SUCCESS_TEACHER";
export const GET_HOMEWORKS_FAIL_TEACHER = "GET_HOMEWORKS_FAIL_TEACHER";

export const POST_HOMEWORKS_REQUEST_TEACHER = "POST_HOMEWORKS_REQUEST_TEACHER";
export const POST_HOMEWORKS_SUCCESS_TEACHER = "POST_HOMEWORKS_SUCCESS_TEACHER";
export const POST_HOMEWORKS_FAIL_TEACHER = "POST_HOMEWORKS_FAIL_TEACHER";

export const DELETE_HOMEWORKS_REQUEST_TEACHER =
  "DELETE_HOMEWORKS_REQUEST_TEACHER";
export const DELETE_HOMEWORKS_SUCCESS_TEACHER =
  "DELETE_HOMEWORKS_SUCCESS_TEACHER";
export const DELETE_HOMEWORKS_FAIL_TEACHER = "DELETE_HOMEWORKS_FAIL_TEACHER";

export const PUT_HOMEWORKS_REQUEST_TEACHER = "PUT_HOMEWORKS_REQUEST_TEACHER";
export const PUT_HOMEWORKS_SUCCESS_TEACHER = "PUT_HOMEWORKS_SUCCESS_TEACHER";
export const PUT_HOMEWORKS_FAIL_TEACHER = "PUT_HOMEWORKS_FAIL_TEACHER";

export const CLEAN_HOMEWORKS_TEACHER = "CLEAN_HOMEWORKS_TEACHER";
