export const GET_LESSONS_REQUEST_TEACHER = "GET_LESSONS_REQUEST_TEACHER";
export const GET_LESSONS_SUCCESS_TEACHER = "GET_LESSONS_SUCCESS_TEACHER";
export const GET_LESSONS_FAIL_TEACHER = "GET_LESSONS_FAIL_TEACHER";

// export const POST_LESSONS_REQUEST_TEACHER = "POST_LESSONS_REQUEST_TEACHER";
// export const POST_LESSONS_SUCCESS_TEACHER = "POST_LESSONS_SUCCESS_TEACHER";
// export const POST_LESSONS_FAIL_TEACHER = "POST_LESSONS_FAIL_TEACHER";

// export const DELETE_LESSONS_REQUEST_TEACHER = "DELETE_LESSONS_REQUEST_TEACHER";
// export const DELETE_LESSONS_SUCCESS_TEACHER = "DELETE_LESSONS_SUCCESS_TEACHER";
// export const DELETE_LESSONS_FAIL_TEACHER = "DELETE_LESSONS_FAIL_TEACHER";

// export const PUT_LESSONS_REQUEST_TEACHER = "PUT_LESSONS_REQUEST_TEACHER";
// export const PUT_LESSONS_SUCCESS_TEACHER = "PUT_LESSONS_SUCCESS_TEACHER";
// export const PUT_LESSONS_FAIL_TEACHER = "PUT_LESSONS_FAIL_TEACHER";
