export const initialStoreValues = {
  sidebarShow: {
    sidebarShow: "responsive",
  },
  toggleDetails: {
    addModal: false,
    updateModal: { status: false, id: 0, effectId: -1 },
    details: [],
    clearInputs: false,
  },
  controlledInput: {
    loading: undefined,
    error: undefined,
    lessonCode: undefined,
    username: undefined,
    emailAddress: undefined,
  },
  userDetails: {
    loading: undefined,
    loadingDetail: undefined,
    userInfo: undefined,
    updateEffects: undefined,
    error: undefined,
    errorAuth: undefined,
  },
  userRegister: {
    loading: undefined,
    success: undefined,
    error: undefined,
  },
  userLogout: {
    loading: undefined,
    success: undefined,
    error: undefined,
  },
  teacherSchool: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    teachers: undefined,
    totalItemCount: undefined,
  },
  studentSchool: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    students: undefined,
    totalItemCount: undefined,
  },
  classroomSchool: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    classrooms: undefined,
    totalItemCount: undefined,
  },
  lessonSchool: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    lessons: undefined,
    totalItemCount: undefined,
  },
  classroomListSchool: {
    loading: undefined,
    classrooms: undefined,
    error: undefined,
  },
  teacherListSchool: {
    loading: undefined,
    teachers: undefined,
    error: undefined,
  },
  lessonTeacher: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    lessons: undefined,
    totalItemCount: undefined,
  },
  examTeacher: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    exams: undefined,
    totalItemCount: undefined,
  },
  homeworkTeacher: {
    loadingGet: undefined,
    errorGet: undefined,
    loadingPost: undefined,
    errorPost: undefined,
    loadingPut: undefined,
    errorPut: undefined,
    loadingDelete: undefined,
    errorDelete: undefined,
    homeworks: undefined,
    totalItemCount: undefined,
  },
  dashboardStats: {
    totalOnline: undefined,
    totalStudent: undefined,
    totalTeacher: undefined,
    totalActiveClassroom: undefined,
  },
};
